name: flutter_tagging_demo
description: A Demo Application of Flutter Tagging.
publish_to: none
version: 1.0.2

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_tagging_plus:
    path: ../
  flutter_syntax_view: ^4.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

